### ISSUE TITLE
Titles with non-latin characters on pages don't always display correctly

### ISSUE THREAD

**Issue by palasso** [Gamah/gBot#26]
# Description

When someone posts a link to the channel, gbot will try to post the title of the website. Some websites use non-latin characters and automatically setting the encoding doesn't always work.
# Expected behavior

user: http://www.clairecords.com/
gbot: ^ 初めて持ったブランドバッグはエルメスバーキン

user: http://www.oceanofdoom.com/
gbot: ^ 1を求めたら10返ってくる！？株の香港上場が評判のフォルスクラブの柔軟性がすごい！

user: http://israblog.nana10.co.il/noblog.htm
gbot: ^ ישרא-בלוג - שגיאה במספר הבלוג
# What actually happens

user: http://www.clairecords.com/
gbot: ^ åãã¦æã£ããã©ã³ãããã°ã¯ã¨ã«ã¡ã¹ãã¼ã­ã³

user: http://www.oceanofdoom.com/
gbot: ^ 1ãæ±ããã10è¿ã£ã¦ããï¼ï¼æ ªã®é¦æ¸¯ä¸å ´ãè©å¤ã®ãã©ã«ã¹ã¯ã©ãã®æè»æ§ããããï¼

user: http://israblog.nana10.co.il/noblog.htm
gbot: ^ éùøà-áìåâ - ùâéàä áîñôø äáìåâ

**Comment by palasso** [comment]
This can be fixed for first 2 examples by setting page.encoding = 'UTF-8' after page = requests.get.

**Comment by Gamah** [comment]
This may be a client issue, 2/3 of the links are working fine on my end.

![image](https://cloud.githubusercontent.com/assets/8608532/11914241/54be69ec-a640-11e5-9335-3440c0f23192.png)

**Comment by palasso** [comment]
Nah, you're using gbot-master on which I already implemented the fix.
I should change the name after I applied a patch on it (since it's not anymore in-sync with master)

(EDIT: name change done)

**Comment by palasso** [comment]
I should change the name after I applied a patch on it (since it's not anymore in-sync with master)

**Comment by palasso** [comment]
After some more testing I see that the third link isn't working because it's using windows-1255 encoding while the page (the html file) is saved with a windows-1252 encoding. The homepage displays Hebrew correctly (with the patch i made) and Hebrew has no problem being displayed at all.
