### ISSUE TITLE
Define best coding practices, development workflow, roadmap and apply to project

### ISSUE THREAD

**Issue by palasso** [Gamah/gBot#30]
#### Use document for new developers

I suggest creating a document `CONTRIBUTING.md` and write there in markdown some coding style practices and development methodologies to use in the project.
#### Coding style

For example should we use `if()` or `if ()`? Should we use `import x.y` or `from x import y`? `( )` or `()` (when left blank)? etc. These examples are real cases where both styles are being used in the code. How about we stick to one and implement it in order to be more consistent?
#### master vs testing

Let's define better which branches are for development, release, testing etc. Maybe make the development branch as default in github (when doing PRs it will select 'default branch' by default).
#### Testing environment

Let's define our test environment (e.g. python3 with these libraries in those distros etc (In arch the requirements would be packages `python`, `python-requests`, `python-urllib3`, `python-lxml`)) and orchestrate it into one channel (#lolbutts)
#### Document past and future development

Maybe we could also have a `CHANGELOG` file to document changes and a `ROADMAP` file to document future to-do's and prioritize on it.

**Comment by Gamah** [comment]
This wasn't actually fixed by the above commit. I'm just bad at git(hub.)

**Comment by Gamah** [comment]
With respect to coding style, do what you like. If I see something that irks me I'll correct it.

To address the specific practices displayed, I prefer the non-space solutions. If(x), func(), etc... I also prefer the "from module import class" syntax.

Commit that will be referenced shortly covers the master v testing and test environment concerns.
